apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-svc-v2
  namespace: default
spec:
  ports:
  - nodePort:
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: myflaskapp
    version: "2"
  type: NodePort
