apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
      - name: myflaskapp
        image: pvass24/myflaskapp:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: USERNAME
          value: "DefaultUser"
        - name: BG_COLOR
          value: "lightblue"
        - name: FONT_COLOR
          value: "white"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
