apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      version: "3"
  template:
    metadata:
      labels:
        version: "3"
    spec:
      containers:
      - name: myflaskapp
        image: pvass24/myflaskapp:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: USERNAME
          value: "DefaultUser"
        - name: BG_COLOR
          value: "lightblue"
        - name: FONT_COLOR
          value: "white"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 100m  # 0.1 CPU cores
          limits:
            cpu: 200m  # 0.2 CPU cores
