apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-deployment-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflaskapp
      version: "1"
  template:
    metadata:
      labels:
        app: myflaskapp
        version: "1"
    spec:
      containers:
      - name: myflaskapp
        image: pvass24/myflaskapp:v1
        ports:
        - containerPort: 5000
        env:
        - name: USERNAME
          value: "DefaultUser"
