apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-svc-v1
  namespace: default
spec:
  ports:
  - nodePort: 
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: myflaskapp
    version: "1"
  type: NodePort
